# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: graphql-api

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: get


# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10

